version: "3"

services:
  notebook:
    build:
      context: .
      dockerfile: Dockerfile
    image: dotnet-jupyter-notebook
    container_name: 100knocks-data-scientist-cs
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - ./work:/home/jovyan/work
    command: start-notebook.sh
